<resources>
    <string name="app_name">TestTask</string>

    <!-- Base Activity -->
    <string name="base_error_no_connection">You still have no internet. Check your connection and try again!</string>

    <!-- Specialities Fragment -->
    <string name="specialities_title">Список специальностей:</string>
    <string name="specialities_id">ID</string>
    <string name="specialities_name">Специальность</string>

    <!-- Employees list Fragment -->
    <string name="employee_title">Список специалистов по специальности:</string>
    <string name="employee_name">Имя</string>
    <string name="employee_last_name">Фамилия</string>
    <string name="employee_age">Возраст</string>
    <string name="employee_age_empty">«\u00AD«</string>

    <!-- EmployeeNetwork detail Fragment -->
    <string name="employee_detail_title">Детальная информация о сотруднике</string>

    <string name="employee_detail_name">Имя</string>
    <string name="employee_detail_last_name">Фамилия</string>
    <string name="employee_detail_birthday">День рождения</string>
    <string name="employee_detail_age">Возраст</string>

    <!-- No connection Dialog -->
    <string name="connection_title">Отсутствует соединение с интернетом!</string>
    <string name="connection_retry">Попробовать ещё раз</string>
    <string name="connection_offline">Продолжить работу оффлайн</string>
    <string name="connection_exit">Выйти</string>

    <!-- Error Dialog -->
    <string name="error_dialog_exit">Завершить работу приложения</string>

    <!-- Error -->
    <string name="error_network_connect">Произошла ошибка при попытке соединиться с сервером.
        Причина:\n\n%s\n\n
        Попробуйте воспользоваться приложением позднее.</string>
    <string name="error_database_select">Произошла ошибка во время извлечения данных из БД.
        Причина:\n\n%s\n\n
        Попробуйте воспользоваться приложением позднее.</string>

</resources>
